[package]
name = "pipico-rs"
version = "0.1.0"
authors = ["Kazuhiko Kikuchi <kazuk.dll@kazuk.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
